name: walletly
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Dev tool for generating flavors (Android/iOS, entrypoints, icons, IDE configs)
  flutter_flavorizr: ^2.4.1

flutter:
  uses-material-design: true

# ------------------------------
# Flavors without Firebase or baseUrl
# ------------------------------
flavorizr:
  app:
    android: true
    ios: true

  flavors:
    dev:
      app:
        name: "Walletly Dev"
      android:
        applicationId: "com.walletly.dev"
        resValues:
          - name: "app_name"
            type: "string"
            value: "Walletly Dev"
      ios:
        bundleId: "com.walletly.dev"
      assets:
        - path: "assets/icons/dev"
      ide: "vscode"

    staging:
      app:
        name: "Walletly Staging"
      android:
        applicationId: "com.walletly.staging"
        resValues:
          - name: "app_name"
            type: "string"
            value: "Walletly Staging"
      ios:
        bundleId: "com.walletly.staging"
      assets:
        - path: "assets/icons/staging"
      ide: "vscode"

    prod:
      app:
        name: "Walletly"
      android:
        applicationId: "com.walletly"
        resValues:
          - name: "app_name"
            type: "string"
            value: "Walletly"
      ios:
        bundleId: "com.walletly"
      assets:
        - path: "assets/icons/prod"
      ide: "vscode"

  instructions:
    - assets:download
    - flavors:android
    - flavors:ios
    - ide:config
    - app:icon
    - app:flavors
